# Generated by Django 3.2.25 on 2024-06-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejsce', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MatkiPszczele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matka', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TypUla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_ula', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PosiadaneUle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=15)),
                ('install_date', models.DateField(verbose_name='data postawienia')),
                ('matka_date', models.DateField(verbose_name='data podania matki')),
                ('ilosc_ramek', models.DecimalField(decimal_places=0, max_digits=15)),
                ('aktywny', models.BooleanField()),
                ('matka', models.ManyToManyField(to='app.MatkiPszczele')),
                ('miejsce', models.ManyToManyField(to='app.Lokalizacja')),
                ('typ_ula', models.ManyToManyField(to='app.TypUla')),
            ],
        ),
    ]
