# Generated by Django 3.2.25 on 2024-05-24 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_post_przegląd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Przegląd',
            new_name='Przeglad',
        ),
    ]
