# Generated by Django 3.2.25 on 2024-06-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240602_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posiadaneule',
            name='ilosc_ramek',
            field=models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2),
        ),
    ]
