# Generated by Django 3.2.25 on 2024-05-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_moviereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedmovies',
            name='review',
        ),
    ]
