# Generated by Django 3.2.25 on 2024-05-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_watchedmovies_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatkiPszczele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matka', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TypUla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_ula', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DodawanieUla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=128)),
                ('install_date', models.DateTimeField(verbose_name='data postawienia')),
                ('matka_date', models.DateTimeField(verbose_name='data podania matki')),
                ('matka', models.ManyToManyField(to='app.MatkiPszczele')),
                ('typ_ula', models.ManyToManyField(to='app.TypUla')),
            ],
        ),
    ]
